### ISSUE TITLE
Update founder info: Dr Long Pham

### ISSUE THREAD

**Issue by dao-duc-tung** [MLOpsVN/mlops.vn#7]
Problem:
- Go to https://mlops.vn/marathon#instructors
- Harry Nguyen is duplicated

Solution:
- Replace the last "Harry Nguyen" by "Long Pham"

**Comment by nvti** [comment]
@dao-duc-tung when I ran the project locally, I saw only 4 people (Harry Nguyen is not duplicated), I don't know why there is a difference between the GitHub code and the code deployed.

And, please attach an image of Dr. Long Pham and the link to her profile. I found a picture on openfactor website but this picture was cropped at the corner.

**Comment by dao-duc-tung** [comment]
@nvti please go to https://mlops.vn/marathon#instructors, not mlops.vn, you will see the this

![image](https://user-images.githubusercontent.com/8639095/221362188-161ba60e-2d9e-488c-a0db-99ca607577c2.png)

Image of Dr. Long Pham is in the Figma design. I put the Figma design link in the task excel sheet
